remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Theory around XFELs
description: Workshop, 24th to 26th September 2025, Campus Pierre et Marie Curie, Sorbonne University, Paris.
