remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Theory around XFELs
description: Workshop, 18th to 20th November 2024, Campus Luminy, Aix-Marseille University, Marseille.
